# Generated by Django 4.1.7 on 2023-02-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('published_year', models.IntegerField()),
                ('acquired', models.BooleanField(default=False)),
                ('thumbnail', models.CharField(blank=True, max_length=1023)),
            ],
        ),
    ]
