# Generated by Django 4.1.7 on 2023-02-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, default='untitled', max_length=255, null=True),
        ),
    ]
