# Generated by Django 4.1.7 on 2023-03-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='acquired',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_year',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
