# Generated by Django 4.1.7 on 2023-03-05 09:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_book_acquired_remove_book_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='acquired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='book',
            name='external_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
