# Generated by Django 4.1.7 on 2023-03-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_book_acquired_book_authors_book_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
